-- Additive Phase 8 payment and physical-Cash semantics.
ALTER TYPE "PaymentType" ADD VALUE 'PURCHASE_PAYMENT';
ALTER TYPE "PaymentType" ADD VALUE 'SUPPLIER_REFUND';
ALTER TYPE "CashMovementType" ADD VALUE 'PURCHASE_PAYMENT';
ALTER TYPE "CashMovementType" ADD VALUE 'PURCHASE_PAYMENT_REVERSAL';
ALTER TYPE "CashMovementType" ADD VALUE 'SUPPLIER_REFUND';
ALTER TYPE "CashMovementType" ADD VALUE 'SUPPLIER_REFUND_REVERSAL';
