export const queryKeys = {
  inventoryDomainRoot: ["inventory"] as const,
  productCategories: ["catalog", "product-categories"] as const,
  productBrands: ["catalog", "product-brands"] as const,
  productAttributes: (categoryId = "all") =>
    ["catalog", "product-attributes", categoryId] as const,
  productsRoot: ["catalog", "products"] as const,
  productDetailsRoot: ["catalog", "product"] as const,
  products: (filters: object) => ["catalog", "products", filters] as const,
  product: (id: string) => ["catalog", "product", id] as const,
  vehicleBrands: ["vehicles", "brands"] as const,
  vehicleModelsRoot: ["vehicles", "models"] as const,
  vehicleModels: (brandId = "all") => ["vehicles", "models", brandId] as const,
  vehiclesRoot: ["vehicles", "list"] as const,
  vehicleDetailsRoot: ["vehicles", "detail"] as const,
  vehicles: (filters: object) => ["vehicles", "list", filters] as const,
  vehicle: (id: string) => ["vehicles", "detail", id] as const,
  compatibilitiesRoot: ["compatibilities"] as const,
  compatibilities: (filters: object) => ["compatibilities", filters] as const,
  productVehicles: (id: string, filters: object) =>
    ["compatibilities", "product", id, filters] as const,
  vehicleProducts: (id: string, filters: object) =>
    ["compatibilities", "vehicle", id, filters] as const,
  locationsRoot: ["inventory", "locations"] as const,
  locations: (filters: object) => ["inventory", "locations", filters] as const,
  inventoryRoot: ["inventory", "balances"] as const,
  inventory: (filters: object) => ["inventory", "balances", filters] as const,
  productInventory: (id: string, filters: object) =>
    ["inventory", "product", id, filters] as const,
  locationInventory: (id: string, filters: object) =>
    ["inventory", "location", id, filters] as const,
  movementsRoot: ["inventory", "movements"] as const,
  movements: (filters: object) => ["inventory", "movements", filters] as const,
  searchRoot: ["search", "products"] as const,
  search: (filters: object) => ["search", "products", filters] as const,
  suppliersRoot: ["purchasing", "suppliers"] as const,
  supplierDetailsRoot: ["purchasing", "supplier"] as const,
  suppliers: (filters: object) => ["purchasing", "suppliers", filters] as const,
  supplier: (id: string) => ["purchasing", "supplier", id] as const,
  supplierAccount: (id: string, filters: object) =>
    ["commercial", "supplier-account", id, filters] as const,
  purchasesRoot: ["purchasing", "purchases"] as const,
  purchaseDetailsRoot: ["purchasing", "purchase"] as const,
  purchases: (filters: object) => ["purchasing", "purchases", filters] as const,
  purchase: (id: string) => ["purchasing", "purchase", id] as const,
  receiptsRoot: ["purchasing", "receipts"] as const,
  receipts: (purchaseId: string, filters: object) =>
    ["purchasing", "receipts", purchaseId, filters] as const,
  receipt: (id: string) => ["purchasing", "receipt", id] as const,
  returnsRoot: ["purchasing", "returns"] as const,
  returns: (purchaseId: string, filters: object) =>
    ["purchasing", "returns", purchaseId, filters] as const,
  purchaseReturnDetailsRoot: ["purchasing", "return"] as const,
  purchaseReturn: (id: string) => ["purchasing", "return", id] as const,
  paymentMethods: (filters: object) => ["finance", "methods", filters] as const,
  paymentMethod: (id: string) => ["finance", "method", id] as const,
  cashSessions: (filters: object) => ["finance", "sessions", filters] as const,
  cashSession: (id: string) => ["finance", "session", id] as const,
  cashRegistersRoot: ["finance", "registers"] as const,
  cashRegisters: (filters: object) => ["finance", "registers", filters] as const,
  cashRegister: (id: string) => ["finance", "register", id] as const,
  currentCashSession: (registerId: string) =>
    ["finance", "register", registerId, "current-session"] as const,
  cashSessionsRoot: ["finance", "sessions"] as const,
  cashSessionDetailsRoot: ["finance", "session"] as const,
  cashSessionSummary: (id: string) =>
    ["finance", "session", id, "summary"] as const,
  cashMovementsRoot: ["finance", "cash-movements"] as const,
  cashMovements: (filters: object) =>
    ["finance", "cash-movements", filters] as const,
  purchasePaymentsRoot: ["finance", "purchase-payments"] as const,
  purchasePayments: (purchaseId: string, filters: object) =>
    ["finance", "purchase-payments", purchaseId, filters] as const,
  supplierRefundsRoot: ["finance", "supplier-refunds"] as const,
  supplierRefunds: (returnId: string, filters: object) =>
    ["finance", "supplier-refunds", returnId, filters] as const,
  payablesRoot: ["commercial", "payables"] as const,
  payables: (filters: object) => ["commercial", "payables", filters] as const,
  supplierAccountsRoot: ["commercial", "supplier-account"] as const,
  customersRoot: ["sales", "customers"] as const,
  customerDetailsRoot: ["sales", "customer"] as const,
  customers: (filters: object) => ["sales", "customers", filters] as const,
  customer: (id: string) => ["sales", "customer", id] as const,
  customerAccount: (id: string, filters: object) =>
    ["commercial", "customer-account", id, filters] as const,
  salesRoot: ["sales", "documents"] as const,
  saleDetailsRoot: ["sales", "document"] as const,
  sales: (filters: object) => ["sales", "documents", filters] as const,
  sale: (id: string) => ["sales", "document", id] as const,
  saleReturnsRoot: ["sales", "returns"] as const,
  saleReturns: (saleId: string, filters: object) =>
    ["sales", "returns", saleId, filters] as const,
  saleReturn: (id: string) => ["sales", "return", id] as const,
  salePaymentsRoot: ["finance", "sale-payments"] as const,
  salePayments: (saleId: string, filters: object) =>
    ["finance", "sale-payments", saleId, filters] as const,
  saleRefundsRoot: ["finance", "sale-refunds"] as const,
  saleRefunds: (returnId: string, filters: object) =>
    ["finance", "sale-refunds", returnId, filters] as const,
  receivablesRoot: ["commercial", "receivables"] as const,
  receivables: (filters: object) => ["commercial", "receivables", filters] as const,
  customerAccountsRoot: ["commercial", "customer-account"] as const,
  commercialSummary: ["commercial-summary"] as const,
  usersRoot: ["administration", "users"] as const,
  users: (filters: object) => ["administration", "users", filters] as const,
  user: (id: string) => ["administration", "user", id] as const,
  userDetailsRoot: ["administration", "user"] as const,
  rolesRoot: ["administration", "roles"] as const,
  role: (id: string) => ["administration", "role", id] as const,
};
