export const PERMISSIONS = {
  USERS_READ: "users.read",
  USERS_CREATE: "users.create",
  USERS_UPDATE: "users.update",
  USERS_ACTIVATE: "users.activate",
  USERS_DEACTIVATE: "users.deactivate",
  ROLES_READ: "roles.read",
  ROLES_MANAGE: "roles.manage",
  PRODUCTS_READ: "products.read",
  PRODUCTS_CREATE: "products.create",
  PRODUCTS_UPDATE: "products.update",
  VEHICLES_READ: "vehicles.read",
  VEHICLES_CREATE: "vehicles.create",
  VEHICLES_UPDATE: "vehicles.update",
  COMPATIBILITIES_READ: "compatibilities.read",
  COMPATIBILITIES_MANAGE: "compatibilities.manage",
  LOCATIONS_READ: "locations.read",
  LOCATIONS_CREATE: "locations.create",
  LOCATIONS_UPDATE: "locations.update",
  INVENTORY_READ: "inventory.read",
  INVENTORY_ADJUST: "inventory.adjust",
  INVENTORY_TRANSFER: "inventory.transfer",
  SEARCH_READ: "search.read",
  SUPPLIERS_READ: "suppliers.read",
  SUPPLIERS_CREATE: "suppliers.create",
  SUPPLIERS_UPDATE: "suppliers.update",
  PURCHASES_READ: "purchases.read",
  PURCHASES_CREATE: "purchases.create",
  PURCHASES_UPDATE: "purchases.update",
  PURCHASES_RECEIVE: "purchases.receive",
  PURCHASES_RETURN: "purchases.return",
  CUSTOMERS_READ: "customers.read",
  CUSTOMERS_CREATE: "customers.create",
  CUSTOMERS_UPDATE: "customers.update",
  SALES_READ: "sales.read",
  SALES_CREATE: "sales.create",
  SALES_UPDATE: "sales.update",
  SALES_POST: "sales.post",
  SALES_RETURN: "sales.return",
} as const;

export const ADMIN_PERMISSIONS = Object.values(PERMISSIONS);
