export const BUSINESS_PERMISSIONS = {
  PRODUCTS_READ: "products.read",
  PRODUCTS_CREATE: "products.create",
  PRODUCTS_UPDATE: "products.update",
  VEHICLES_READ: "vehicles.read",
  VEHICLES_CREATE: "vehicles.create",
  VEHICLES_UPDATE: "vehicles.update",
  COMPATIBILITIES_READ: "compatibilities.read",
  COMPATIBILITIES_MANAGE: "compatibilities.manage",
  LOCATIONS_READ: "locations.read",
  LOCATIONS_CREATE: "locations.create",
  LOCATIONS_UPDATE: "locations.update",
  INVENTORY_READ: "inventory.read",
  INVENTORY_ADJUST: "inventory.adjust",
  INVENTORY_TRANSFER: "inventory.transfer",
  SEARCH_READ: "search.read",
} as const;
